const AuthActions = {
  IS_AUTHED: 'IS_AUTHED',
  NOT_AUTHED: 'NOT_AUTHED',
  LOGGING_OUT: 'LOGGING_OUT',
  AUTHENTICATING: 'AUTHENTICATING',
  RECEIVE_USER_DATA: 'RECEIVE_USER_DATA',
};

const EventActions = {
  LOAD_EVENTS: 'LOAD_EVENTS',
  LOAD_ALL_EVENTS: 'LOAD_ALL_EVENTS',
  LOAD_EVENTS_BY_ORG: 'LOAD_EVENTS_BY_ORG',
  LOAD_EVENTS_BY_DATE: 'LOAD_EVENTS_BY_DATE',
  LOAD_EVENTS_BY_EPOCH: 'LOAD_EVENTS_BY_EPOCH',
};

const OrgActions = {
  LOAD_ORGS: 'LOAD_ORGS',
};

export default { AuthActions, EventActions, OrgActions };
